name: CI

on: 
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
          GITHUB_LIST: ${{ toJson(github.event_name) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$GITHUB_LIST"
